name: Terraform provider cache example

on:
  workflow_dispatch:

jobs:
  main:
    name: Example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_version: 0.67.0
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
          tf_version: 1.7.5
      - name: Set TG_PROVIDER_CACHE
        run: |
          echo "TG_PROVIDER_CACHE=1" >>"$GITHUB_ENV"
        
      - name: Cache Terraform
        uses: actions/cache@v4
        with:
          path: |
            .terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-
      - name: Init Terraform configuration
        run: |
          terragrunt init
