name: Terraform provider cache example

on:
  push:
  workflow_dispatch:

# env:
#   TERRAGRUNT_PROVIDER_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache

jobs:
  main:
    name: Example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Install Terragrunt
        run: |
          wget -qO- https://github.com/gruntwork-io/terragrunt/releases/download/v0.76.5/terragrunt_linux_amd64 > /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt
          
      - name: Verify Terragrunt Installation
        run: |
          which terragrunt
          terragrunt --version
          
      - name: Set Timestamp Variable
        id: date
        run: echo "CACHE_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: mkdir folder
        run: mkdir -p "$HOME/.terraform.d/plugin-cache"
      
      - name: Cache Terraform
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
          key: terraform-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ runner.os }}-

      - name: Debug Cache Path Before Init
        run: ls -alh $HOME/.terraform.d/plugin-cache
      # - name: Check Cached Provider After Init
      #   run: echo $TERRAGRUNT_PROVIDER_CACHE_DIR
      
      - name: Init Terraform configuration
        run: |
          terragrunt init
      # - name: Save Terraform Cache
      #   uses: actions/cache/save@v4
      #   with:
      #     path: ${{ env.TERRAGRUNT_PROVIDER_CACHE_DIR }}
      #     key: terragrunt-cache-${{ runner.os }}-${{ env.CACHE_DATE }}


