name: Terraform provider cache example

on:
  push:
  workflow_dispatch:

env:
  TG_PROVIDER_CACHE_DIR: ${{ github.workspace }}/.terraform.d/plugin-cache
  TERRAGRUNT_DOWNLOAD_DIR: ${{ github.workspace }}/.terragrunt-cache

jobs:
  main:
    name: Example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Install Terragrunt
        run: |
          wget -qO- https://github.com/gruntwork-io/terragrunt/releases/download/v0.76.5/terragrunt_linux_amd64 > /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt
          
      - name: Verify Terragrunt Installation
        run: |
          which terragrunt
          terragrunt --version
          
      - name: Set Timestamp Variable
        id: date
        run: |
          echo "CACHE_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        

      # - name: mkdir folder
      #   run: |
      #     mkdir -p ${{ env.TG_PROVIDER_CACHE_DIR }} 
      
      - name: Cache Terraform
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.TG_PROVIDER_CACHE_DIR }}
          key: terragrunt-cache-${{ runner.os }}-${{ env.CACHE_DATE }}
          restore-keys: |
            terragrunt-cache-${{ runner.os }}-

      - name: Debug Cache Path Before Init
        run: ls -alh ${{ env.TG_PROVIDER_CACHE_DIR }}
      
      - name: Init Terraform configuration
        run: |
          terragrunt run-all init --non-interactive --provider-cache --provider-cache-dir ${{ env.TG_PROVIDER_CACHE_DIR }}
      - name: Save Terraform Cache
        uses: actions/cache/save@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: terragrunt-cache-${{ runner.os }}-${{ env.CACHE_DATE }}


