name: Terraform provider cache example

on:
  push

jobs:
  main:
    name: Example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Install Terragrunt
        run: |
          wget -qO- https://github.com/gruntwork-io/terragrunt/releases/download/v0.67.0/terragrunt_linux_amd64 > /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt

      - name: Verify Terragrunt Installation
        run: |
          which terragrunt
          terragrunt --version

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tg_version: 0.67.0
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
          tf_version: 1.7.5

      - name: Set TG_PROVIDER_CACHE
        run: |
          mkdir /home/runner/.terragrunt-cache
          echo "TG_PROVIDER_CACHE=1" >>"$GITHUB_ENV"
          echo "TF_PLUGIN_CACHE_DIR=/home/runner/.terragrunt-cache" >> $GITHUB_ENV    
          
      - name: Set Timestamp Variable
        id: date
        run: echo "CACHE_DATE=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Restore Terraform Cache
        uses: actions/cache/restore@v4
        with:
          path: /home/runner/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ env.CACHE_DATE }}-${{ hashFiles('**/*.hcl') }}
          restore-keys: |
            ${{ runner.os }}-terragrunt-
            
      - name: Verify Provider Cache Structure
        run: |
          echo "Checking provider cache structure..."
          find /home/runner/.terragrunt-cache/registry.terraform.io -type f
            
      - name: Init Terraform configuration
        run: |
          ls -lah "$TF_PLUGIN_CACHE_DIR"
          terragrunt run-all init --terragrunt-non-interactive --terragrunt-provider-cache --terragrunt-provider-cache-dir "$TF_PLUGIN_CACHE_DIR"
        
      # - name: Ensure Terragrunt cache directory exists
      #   run: |
      #     cat ~/.terragrunt-cache/registry.terraform.io/hashicorp/aws/5.38.0/linux_amd64/terraform-provider-aws_v5.38.0_x5
          
      - name: Save Terraform Cache
        uses: actions/cache/save@v4
        with:
          path: /home/runner/.terragrunt-cache
          key: ${{ runner.os }}-terragrunt-${{ env.CACHE_DATE }}-${{ hashFiles('**/*.hcl') }}

         

